"use client";

import { useState, useMemo } from "react";
import {
  X,
  FileText,
  FileSpreadsheet,
  Sparkles,
  Loader2,
  Calendar,
  Percent,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";
import type { GestionMensualResponse, IndicadorOsiItem } from "@/types";
import { exportIndicadoresToExcel } from "@/lib/export-indicadores-xlsx";

interface Props {
  isOpen: boolean;
  onClose: () => void;
  data: GestionMensualResponse;
  initialMes: string;
}

export default function ExportIndicadoresModal({
  isOpen,
  onClose,
  data,
  initialMes,
}: Props) {
  const [selectedMes, setSelectedMes] = useState(initialMes || data.meses[0]?.mes || "");
  const [metaPorcentaje, setMetaPorcentaje] = useState(85);
  const [observaciones, setObservaciones] = useState("");
  const [isPdfLoading, setIsPdfLoading] = useState(false);
  const [isXlsxLoading, setIsXlsxLoading] = useState(false);

  // Month info
  const mesData = useMemo(() => {
    return (
      data.meses.find((m) => m.mes === selectedMes) ||
      data.meses[data.meses.length - 1] ||
      data.total
    );
  }, [data, selectedMes]);

  const selectedMesLabel = mesData.label;

  // Auto-generate suggested observation draft based on actual data
  const handleAutoGenerateDraft = () => {
    const lines: string[] = [];

    lines.push(
      `Total OSI recibidas: ${mesData.osisRecibidas} OSI del mes de ${selectedMesLabel.toUpperCase()}.`
    );

    if (mesData.osisEjecutadasEnSuMes > 0) {
      lines.push(
        `Se ejecutaron satisfactoriamente ${mesData.osisEjecutadasEnSuMes} OSI dentro del mes previsto.`
      );
    }

    if (mesData.osisRezagadasEjecutadas > 0) {
      lines.push(
        `Se ejecutaron ${mesData.osisRezagadasEjecutadas} OSI rezagadas de periodos anteriores.`
      );
    }

    // Check pending OSIs in metricOsis
    const pendingKey = `pendientes_${selectedMes}`;
    const pendingItems = data.metricOsis?.[pendingKey] ?? [];

    if (pendingItems.length > 0) {
      const summaryList = pendingItems
        .slice(0, 5)
        .map((item) => `${item.nroOsi} (${item.empresa})`)
        .join(", ");
      lines.push(
        `OSI pendientes por ejecutar (${pendingItems.length}): ${summaryList}${
          pendingItems.length > 5 ? `, entre otras` : ""
        }. Pendientes de reprogramación o por coordinar con cliente.`
      );
    }

    if (mesData.participantesPlanificados > 0) {
      lines.push(
        `Participación: ${mesData.participantesLista} participantes asistieron y fueron certificados de un total de ${mesData.participantesPlanificados} participantes según OSI.`
      );
    }

    setObservaciones(lines.join(" "));
  };

  const handleDownloadPdf = async () => {
    try {
      setIsPdfLoading(true);
      const { pdf } = await import("@react-pdf/renderer");
      const { default: IndicadorCalidadPdfDocument } = await import(
        "@/lib/indicador-calidad-pdf-document"
      );

      const blob = await pdf(
        <IndicadorCalidadPdfDocument
          data={data}
          selectedMes={selectedMes}
          selectedMesLabel={selectedMesLabel}
          metaPorcentaje={metaPorcentaje}
          observaciones={observaciones}
        />
      ).toBlob();

      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `Indicador_de_calidad_${data.year}_${selectedMesLabel.replace(/\s+/g, "_")}.pdf`;
      link.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Error generating PDF:", err);
      alert("Ocurrió un error al generar el PDF. Por favor reintente.");
    } finally {
      setIsPdfLoading(false);
    }
  };

  const handleDownloadXlsx = () => {
    try {
      setIsXlsxLoading(true);
      exportIndicadoresToExcel({
        data,
        selectedMes,
        selectedMesLabel,
        metaPorcentaje,
        observaciones,
      });
    } catch (err) {
      console.error("Error exporting to Excel:", err);
      alert("Ocurrió un error al generar el archivo Excel.");
    } finally {
      setIsXlsxLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm animate-in fade-in duration-150"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="bg-white rounded-2xl shadow-2xl border border-gray-200 w-full max-w-2xl max-h-[92vh] flex flex-col overflow-hidden animate-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="px-6 py-5 border-b border-gray-100 flex items-start justify-between bg-gradient-to-r from-sky-50 via-white to-gray-50">
          <div className="flex items-center gap-3">
            <span className="p-2.5 rounded-xl bg-sky-600 text-white shadow-sm">
              <FileText className="w-5 h-5" />
            </span>
            <div>
              <h3 className="text-base font-bold text-gray-900 leading-tight">
                Indicador de calidad
              </h3>
              <p className="text-xs font-semibold text-sky-700 mt-0.5">
                Planificación y ejecución de la capacitación
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-gray-400 hover:text-gray-600 hover:bg-gray-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 space-y-5 text-xs text-gray-700">
          {/* Controls Row */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block font-semibold text-gray-700 mb-1.5">
                <span className="flex items-center gap-1.5">
                  <Calendar className="w-3.5 h-3.5 text-gray-400" />
                  Mes de Evaluación
                </span>
              </label>
              <select
                value={selectedMes}
                onChange={(e) => setSelectedMes(e.target.value)}
                className="w-full px-3 py-2 rounded-lg border border-gray-200 bg-white font-medium text-gray-800 focus:outline-none focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500"
              >
                {data.meses.map((m) => (
                  <option key={m.mes} value={m.mes}>
                    {m.label} ({data.year})
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block font-semibold text-gray-700 mb-1.5">
                <span className="flex items-center gap-1.5">
                  <Percent className="w-3.5 h-3.5 text-gray-400" />
                  Meta Calidad (%)
                </span>
              </label>
              <input
                type="number"
                min="1"
                max="100"
                value={metaPorcentaje}
                onChange={(e) => setMetaPorcentaje(Number(e.target.value) || 85)}
                className="w-full px-3 py-2 rounded-lg border border-gray-200 bg-white font-medium text-gray-800 focus:outline-none focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500"
              />
            </div>
          </div>

          {/* Quick Preview Card */}
          <div className="p-3.5 rounded-xl bg-gray-50 border border-gray-200/80 flex items-center justify-between text-xs">
            <div>
              <div className="text-gray-500 font-medium">Resumen del Periodo:</div>
              <div className="font-bold text-gray-900 mt-0.5 text-sm">
                {selectedMesLabel} · {mesData.osisRecibidas} Recibidas · {mesData.osisEjecutadasEnSuMes} Ejecutadas · {mesData.osisPendientes} Pendientes
              </div>
            </div>
            <div className="text-right">
              <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-bold bg-sky-100 text-sky-800">
                Meta: {metaPorcentaje}%
              </span>
            </div>
          </div>

          {/* Observaciones Input with AI / Smart Auto-Draft */}
          <div>
            <div className="flex items-center justify-between mb-1.5">
              <label className="block font-semibold text-gray-700">
                Observaciones y Justificaciones
              </label>
              <button
                type="button"
                onClick={handleAutoGenerateDraft}
                className="inline-flex items-center gap-1 text-[11px] font-semibold text-sky-600 hover:text-sky-800 hover:underline"
                title="Generar redacción sugerida basada en los datos del mes"
              >
                <Sparkles className="w-3.5 h-3.5 text-sky-500" />
                Generar borrador automático
              </button>
            </div>
            <textarea
              rows={4}
              value={observaciones}
              onChange={(e) => setObservaciones(e.target.value)}
              placeholder="Ejemplo: Total OSI recibidas: 49. La OSI 3286 impartió una sesión en mayo y otra quedó para junio. Las OSI 3295 y 3293 fueron suspendidas por solicitud del cliente..."
              className="w-full p-3 rounded-lg border border-gray-200 bg-white text-xs text-gray-800 focus:outline-none focus:ring-2 focus:ring-sky-500/20 focus:border-sky-500 placeholder:text-gray-400"
            />
            <p className="text-[11px] text-gray-400 mt-1">
              Este texto se incluirá en el cuadro de OBSERVACIONES del documento PDF y Excel.
            </p>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 border-t border-gray-100 bg-gray-50/70 flex items-center justify-between gap-3">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-white border border-gray-200 text-gray-700 font-medium hover:bg-gray-100 transition-colors shadow-sm text-xs"
          >
            Cancelar
          </button>

          <div className="flex items-center gap-2.5">
            <button
              onClick={handleDownloadXlsx}
              disabled={isXlsxLoading}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-emerald-600 text-white font-semibold hover:bg-emerald-700 transition-colors shadow-sm text-xs disabled:opacity-50"
            >
              {isXlsxLoading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <FileSpreadsheet className="w-4 h-4" />
              )}
              <span>Descargar Excel</span>
            </button>

            <button
              onClick={handleDownloadPdf}
              disabled={isPdfLoading}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-sky-600 text-white font-semibold hover:bg-sky-700 transition-colors shadow-sm text-xs disabled:opacity-50"
            >
              {isPdfLoading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <FileText className="w-4 h-4" />
              )}
              <span>Descargar PDF</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
