// Build-time version generator.
//
// Derives a version string from git (tag, short SHA, commit count, branch, date)
// and writes lib/version.generated.ts. The Footer (and anything else) imports it
// to display the running build's version.
//
// Run automatically before `next dev` (predev) and `next build` (prebuild). Also
// safe to run manually: `node scripts/generate-version.mjs`.
//
// The version NUMBER always comes from package.json (bumped by `npm run release`).
// Git only adds precision (commit SHA, distance from tag) when available; if git is
// missing or fails, every call degrades gracefully via APP_* env vars and then safe
// defaults. The script never throws, so it can never break a build.

import { execSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = resolve(__dirname, "..", "lib", "version.generated.ts");

// Run a git command and return trimmed stdout, or `fallback` on any failure.
function git(args, fallback = "") {
  try {
    return execSync(`git ${args}`, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch {
    return fallback;
  }
}

// Read package.json version so the displayed version always tracks it.
function readPackageVersion() {
  try {
    const pkg = JSON.parse(readFileSync(resolve(__dirname, "..", "package.json"), "utf8"));
    return pkg.version || "0.0.0";
  } catch {
    return "0.0.0";
  }
}

const pkgVersion = readPackageVersion();

const describe = git("describe --tags --always", process.env.APP_DESCRIBE || "");
const commit = git("rev-parse --short HEAD", process.env.APP_COMMIT || "unknown");
const commitCount = git("rev-list --count HEAD", process.env.APP_COMMIT_COUNT || "0");
const branch = git("branch --show-current", process.env.APP_BRANCH || "unknown");
const date = git("log -1 --format=%cI", process.env.APP_BUILD_DATE || new Date().toISOString());
const tag = git("describe --tags --abbrev=0", process.env.APP_TAG || "");

// Human-friendly version label.
//
// package.json is the AUTHORITATIVE source of the version number — it is bumped by
// `npm run release` (commit-and-tag-version) and is always available. Git is only ever
// used to add *extra precision* (which commit, how far past the tag), never for
// correctness. This guarantees a correct version even where git is unavailable, e.g.
// a Docker builder without the git binary installed.
//
//   - git available + tagged  -> "v1.5.0-3-g6238fcf" (exact commit, distance from tag)
//   - git available, no tags  -> "v1.5.0+6238fcf"    (package version + commit)
//   - no git at all           -> "v1.5.0"            (package version; still correct)
const baseVersion = process.env.APP_VERSION || `v${pkgVersion}`;
let versionLabel;
if (describe && describe !== commit) {
  versionLabel = describe; // tag-based, e.g. v1.5.0-3-g6238fcf
} else if (commit !== "unknown") {
  versionLabel = `${baseVersion}+${commit}`;
} else {
  versionLabel = baseVersion;
}

const payload = {
  version: versionLabel,
  describe: describe || commit,
  commit,
  commitCount: Number.parseInt(commitCount, 10) || 0,
  branch,
  date,
  tag,
};

const content = `// AUTO-GENERATED by scripts/generate-version.mjs — do not edit by hand.
// Regenerated before every \`npm run dev\` (predev) and \`npm run build\` (prebuild).
export const APP_VERSION = ${JSON.stringify(payload, null, 2)} as const;
export default APP_VERSION;
`;

await mkdir(dirname(OUT_FILE), { recursive: true });
await writeFile(OUT_FILE, content, "utf8");

console.log(`[generate-version] wrote ${OUT_FILE}`);
console.log(`[generate-version] version=${payload.version} commit=${payload.commit} count=${payload.commitCount} branch=${payload.branch} tag=${payload.tag || "(none)"}`);
